**How to create a NUll values in a data**

- None
- np.nan

In [2]:
import numpy as np
import pandas as pd

In [9]:
d={'Names':['Ramesh','Suresh',None,'Mahesh'],
    'Age':[None,22,24,25],
    'City':['Hyd','Blr','Pune',None]}
df1=pd.DataFrame(d)
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2     NaN  24.0  Pune
3  Mahesh  25.0   NaN

In [10]:
df1.to_csv('data1.csv',index=False)

In [11]:
d={'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
    'Age':[None,22,24,25],
    'City':['Hyd','Blr','Pune',np.nan]}
df2=pd.DataFrame(d)
df2.to_csv('data2.csv',index=False)

- Categorical data us **None**
- Numerical data us **np.nan**

In [12]:
df1.isnull()
# isnull :  wherver null value is there it display as True

   Names    Age   City
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [13]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [14]:
df1
df1.values
df1.dtypes
df1.isnull()
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**Fill The Values**

In [15]:
# Random filing
df1.fillna(30)

    Names   Age  City
0  Ramesh  30.0   Hyd
1  Suresh  22.0   Blr
2      30  24.0  Pune
3  Mahesh  25.0    30

In [16]:
# Select one column and fill with value
df1.fillna(30)
df1['City'].fillna('Delhi')
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2     NaN  24.0  Pune
3  Mahesh  25.0   NaN

In [24]:
# (pad,ffill) , (bfill,backfill)
# axis=0 axis=1
df1.fillna(method='pad')
df1.fillna(method='pad',axis=1)

df1.fillna(method='bfill')
df1.fillna(method='bfill',axis=1)

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [25]:
df1.ffill()          # instead of method='pad'/'ffill'
df1.bfill()           # instead of method='bfill'/'backfill'
df1.ffill(axis=1)
df1.bfill(axis=1)

    Names   Age  City
0  Ramesh   Hyd   Hyd
1  Suresh  22.0   Blr
2    24.0  24.0  Pune
3  Mahesh  25.0   NaN

In [28]:
df1.ffill()

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2  Suresh  24.0  Pune
3  Mahesh  25.0  Pune

- mean
- median
- mode

In [18]:
age_mean=df1['Age'].mean()
df1['Age'].fillna(age_mean)

0    23.666667
1    22.000000
2    24.000000
3    25.000000
Name: Age, dtype: float64

**Situation-1**

In [ ]:
# There is No particular Rule how to fill the missing values
# It is completely based on situation

In [3]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])

In [4]:
d1 # I want to handover this data to my students with not encode

   Gender
0    Male
1  Female
2     NaN

In [6]:
d={'Female':0,'Male':1}
d1['Gender']=d1['Gender'].map(d)
d1

   Gender
0     1.0
1     0.0
2     NaN

In [7]:
# The student think that I want to fill a missing
# data is numerical :mean
(1+0)/2

0.5

**Situation-2**

In [8]:
# Ml algorithm
# Churn : stay or not stay
churn=['stay','not_stay',None]
churn=[0,1,None]
churn=[0,1,0.5]

**Situation-3**

In [10]:
# No of days
[20,25,np.nan,31]
(20+25+31)/3

25.333333333333332

**Situation-4**

In [11]:
course=['DS','AI','DS','Devops','AI','Devops','AI']
fee=[30000,27000,30000,22000,30000,22000,np.nan]
pd.DataFrame(zip(course,fee))

# First group by with course
# then take corresponding course values only

        0        1
0      DS  30000.0
1      AI  27000.0
2      DS  30000.0
3  Devops  22000.0
4      AI  30000.0
5  Devops  22000.0
6      AI      NaN

**KNNImputer**

- KNN : K-nearest neighbours

- Where k is a number

- instead of taking avg of all the values data
    
    - first will find the neighbours who are close with missing data
    
    - by using Euclidian distance calculation will identify the neighbour rows
    
    - suppose k=2 will identify the two closest rows
    
    - those closest rows values will take it,will calculate the mean
    
    - finally will fill with the mean

In [14]:
Salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(Salary,age),
               columns=['Salary','Age'])
df

    Salary  Age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

- sklearn
    - impute
        - KNNImputer

In [15]:
from sklearn.impute import KNNImputer
imputer= KNNImputer(n_neighbors=2)
pd.DataFrame(imputer.fit_transform(df))

         0     1
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0

**try below**

- CharacterTextSploter(separator="\n\n")

- CharacterTextSploter(separator="\n") 

- CharacterTextSploter(separator=" ")  

- the above three expects not only separator

        - Chunk size
        - Overlap

- Data read 
- Data cleaning
- Data analysis 
- Feature engineering
- Feature selection
- Model development
- Model evaluation
- Model tuning 
- Model deployment