**10 Aug 2026**

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

visa_df=pd.read_csv(r"C:\Users\vaish\Documents\NareshIT\GEN_AI\Data_Files\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [32]:
num = visa_df.select_dtypes(exclude='str').columns
cat = visa_df.select_dtypes(include='str').columns

In [ ]:
Data read
    |
Data cleaning
    |
Data Analysis
    |
Feature engineering
    |
Feature Selection
    |
Model development
    |
Model evaluation
    |
Model tuning
    |
Model deployment

**Feature Engineering**

- so far we have performed 
    
    - Data frame quick checks
    
    - Categorical column analysis
    
    - Bar charts , pie charts
   
    - Numerical column analysis
    
    - Histograms, Box plots , Outliers
    
    - Bi-multi variate analysis
   
    - correlation etc......


- Now we need to learn Feature Engineering
   
    - we will create a new columns for better ML models
    
    - we will perform the **Encoding** , which is convert Categorical to Numerical sat
    
    - we will do data **Transformation**
    
    - we will perform **Scaling : Standardization and Normalization**
    
    - we will perform the **Missing Value Analysis**


- Simply feature engineering means our data will be modified

**Case_Status**

In [20]:
# first check how many unique labels are there in case_status
visa_df['case_status'].unique()

<ArrowStringArray>
['Denied', 'Certified']
Length: 2, dtype: str

In [21]:
# Create a dictinory
d={'Certified':0,'Denied':1}

In [22]:
# map the above the dictionary with original column
visa_df['case_status']= visa_df['case_status'].map(d)

In [23]:
visa_df['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [24]:
labels=sorted(visa_df['education_of_employee'].unique())
d={j:i for i,j in enumerate(labels)}
d

{"Bachelor's": 0, 'Doctorate': 1, 'High School': 2, "Master's": 3}

In [25]:
labels=sorted(visa_df['education_of_employee'].unique())
d={j:i for i,j in enumerate(labels)}
visa_df['education_of_employee'].map(d)

0        2
1        3
2        0
3        0
4        3
        ..
25475    0
25476    2
25477    3
25478    3
25479    0
Name: education_of_employee, Length: 25480, dtype: int64

- There are two Encodings
    
    - LabelEncoder
    
    - OrdinalEncoder

In [26]:
# Read The Data Again
visa_df=pd.read_csv(r"C:\Users\vaish\Documents\NareshIT\GEN_AI\Data_Files\Visadataset.csv")

- sklearn : **Package**
    
    - preprocessing : **Module**
        
      - LabelEncoder : **Class**
             
         - fit_transform : **method**

In [ ]:
import sklearn
sklearn.preprocessing

from sklearn import preprocessing
dir(preprocessing) : LabelEncoder
preprocessing.LabelEncoder

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform()

# Read The Class
# Save The Class
# Apply The Fit Transform

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=Label.Encoder()
le.fit_transform

from sklearn.preprocessing import LabelEncoder
oe=OrdinalEncoder()
oe.fit_transform

**Fit transform**

- fit : created a dictionary(find something)

- transform: using above finding we are modify the data

from sklearn.module import class

va=class()

va.fit or va.fit_transform

**11 Aug 2026**

**LableEncoder**

In [29]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['case_status']=le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0], shape=(25480,))

In [30]:
visa_df=pd.read_csv(r"C:\Users\vaish\Documents\NareshIT\GEN_AI\Data_Files\Visadataset.csv")

In [ ]:
# when to use ordinal column 
# when to use labelEncoder column & when to use Nominal
# important questions in interview

In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:       # Dont consider caseID
    visa_df[i]=le.fit_transform(visa_df[i])

visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [36]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
for i in cat[1:]:       # Dont consider caseID
    visa_df[i]=oe.fit_transform(visa_df[[i]])

visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1.0,2.0,0.0,0.0,14513,2007,4.0,592.2029,0.0,1.0,1.0
1,EZYV02,1.0,3.0,1.0,0.0,2412,2002,2.0,83425.6500,3.0,1.0,0.0
2,EZYV03,1.0,0.0,0.0,1.0,44444,2008,4.0,122996.8600,3.0,1.0,1.0
3,EZYV04,1.0,0.0,0.0,0.0,98,1897,4.0,83434.0300,3.0,1.0,1.0
4,EZYV05,0.0,3.0,1.0,0.0,1082,2005,3.0,149907.3900,3.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1.0,0.0,1.0,1.0,2601,2008,3.0,77092.5700,3.0,1.0,0.0
25476,EZYV25477,1.0,2.0,1.0,0.0,3274,2006,2.0,279174.7900,3.0,1.0,0.0
25477,EZYV25478,1.0,3.0,1.0,0.0,1121,1910,3.0,146298.8500,3.0,0.0,0.0
25478,EZYV25479,1.0,3.0,1.0,1.0,1918,1887,4.0,86154.7700,3.0,1.0,0.0
25479,EZYV25480,1.0,0.0,1.0,0.0,3195,1960,1.0,70876.9100,3.0,1.0,0.0

In [37]:
visa_df=pd.read_csv(r"C:\Users\vaish\Documents\NareshIT\GEN_AI\Data_Files\Visadataset.csv")

**pd.get_dummies**

- get dummies is a way to reprsent the categorical columns to numerical

- first it will check what are the labels in a column

- for example case status has two labels
    - Denied and Certified

- so it will create two new columns based on labels
    - col1: case_status_Denied
    - col2: case_status_Certified

**It is also called as One Hot Encoder**

- It makes new colums are independent each other
- Some of ML algorithms expect that columns should be **Independent** each other

In [38]:
pd.get_dummies(visa_df['case_status'],dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]