In [9]:
# important
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
Names=['Ramesh','Suresh','Satish','Mahesh']
Age=[20,22,24,26]

**Step-1:Create a Dataframe**

In [ ]:
Extract transform load
ETL is a process 
EDA data Analysis    # both are different

In [11]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [12]:
# pd.DataFrame(data,index,columns,dtype,copy)

pd.DataFrame(Names) 
# pd.DataFrame(Names,'Names') # Names assume as index
# pd.DataFrame(Names,columns=''Names) # Columns array
pd.DataFrame(Names,columns=['Names'])

    Names
0  Ramesh
1  Suresh
2  Satish
3  Mahesh

In [13]:
# pd.DataFrame(data,index,columns,dtype,copy)
pd.DataFrame(Names)
pd.DataFrame(Names,columns=['Names'])
pd.DataFrame(Names,
             index=['A','B','C','D'],
            columns=['Names'])

    Names
A  Ramesh
B  Suresh
C  Satish
D  Mahesh

In [14]:
Names=['Ramesh','Suresh','Satish','Mahesh']
Age=[20,22,24,26]
DATA=[Names,Age]
pd.DataFrame(DATA).T

        0   1
0  Ramesh  20
1  Suresh  22
2  Satish  24
3  Mahesh  26

In [15]:
Names=['Ramesh','Suresh','Satish','Mahesh']
Age=[20,22,24,26]
DATA=zip(Names,Age)
pd.DataFrame(DATA,columns=['Names','Age'])

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24
3  Mahesh   26

**Step-2: Add a new column to already an existed df**

In [16]:
Names=['Ramesh','Suresh','Satish','Mahesh']
Age=[20,22,24,26]
DATA=zip(Names,Age)
df=pd.DataFrame(DATA,columns=['Names','Age'])

In [17]:
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24
3  Mahesh   26

In [ ]:
df[col_name]
# Selection
# Updation
# Creation

In [18]:
df['Names']

0    Ramesh
1    Suresh
2    Satish
3    Mahesh
Name: Names, dtype: str

In [19]:
df['Age']=[30,32,34,36]
df

    Names  Age
0  Ramesh   30
1  Suresh   32
2  Satish   34
3  Mahesh   36

In [20]:
df['City']=['Hyd','Pune','Blr','Bihata']
df

    Names  Age    City
0  Ramesh   30     Hyd
1  Suresh   32    Pune
2  Satish   34     Blr
3  Mahesh   36  Bihata

In [21]:
df['Gender']=['Male','Male','Male','Male']
df

    Names  Age    City Gender
0  Ramesh   30     Hyd   Male
1  Suresh   32    Pune   Male
2  Satish   34     Blr   Male
3  Mahesh   36  Bihata   Male

In [ ]:
df()

**30 July 2026**

- created a dataframe with one column
- learned how to add a column names
- learned how to change the index
- created a dataframe with two colums using zip
- understood how to select, update and creat new column with already existed dataframe

**Step-3 : How to add data to empry dataframe**

In [22]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [23]:
df["Names"]=["Ramesh","suresh","Satish"]
df["Age"]=[20,24,26]
df["City"]=["Hyd","Blr","Chennai"]
df

    Names  Age     City
0  Ramesh   20      Hyd
1  suresh   24      Blr
2  Satish   26  Chennai

**Step-4 : Create a Dataframe using Dictionary**

In [24]:
d={"Names":["Ramesh","suresh","Satish"],
   "Age":[20,24,26],
    "City":["Hyd","Blr","Chennai"]}
d

{'Names': ['Ramesh', 'suresh', 'Satish'],
 'Age': [20, 24, 26],
 'City': ['Hyd', 'Blr', 'Chennai']}

In [26]:
df=pd.DataFrame(d)
df
# Keys become colums 
# Values become rows

    Names  Age     City
0  Ramesh   20      Hyd
1  suresh   24      Blr
2  Satish   26  Chennai

In [ ]:
d={'Names':'Ramesh',
   'Age':20,
    'City':'Hyd'}
df=pd.DataFrame(d)  # Error : If using all scalar values, you must pass an index

In [28]:
d={'Names':'Ramesh',
   'Age':20,
    'City':'Hyd'}
df=pd.DataFrame(d,index=[0,1,2])
df

    Names  Age City
0  Ramesh   20  Hyd
1  Ramesh   20  Hyd
2  Ramesh   20  Hyd

**Step-5: drop a new column**

In [29]:
df["Names"]=["Ramesh","suresh","Satish"]
df["Age"]=[20,24,26]
df["City"]=["Hyd","Pune","Delhi"]
df

    Names  Age   City
0  Ramesh   20    Hyd
1  suresh   24   Pune
2  Satish   26  Delhi

In [ ]:
df.drop(Lables,axis=0,index,columns,inplace=True) # Index
# default behaviour
# default it is consider index or column
# Doc string shift+tab

In [30]:
df.drop('City')

KeyError: "['City'] not found in axis"

In [31]:
df.drop('City',axis=1)
# inplace  = False
# inplace =  True overwrite the output in same df

    Names  Age
0  Ramesh   20
1  suresh   24
2  Satish   26

In [32]:
df.drop(colums=['City'])

TypeError: DataFrame.drop() got an unexpected keyword argument 'colums'. Did you mean 'columns'?

In [33]:
df.drop(2)

    Names  Age  City
0  Ramesh   20   Hyd
1  suresh   24  Pune

In [34]:
df.drop(2,axis=1)

KeyError: '[2] not found in axis'

In [35]:
df.drop(2,axis=0)

    Names  Age  City
0  Ramesh   20   Hyd
1  suresh   24  Pune

In [36]:
df.drop(index=[2])

    Names  Age  City
0  Ramesh   20   Hyd
1  suresh   24  Pune

In [ ]:
df.drop(lables,axis)
df.drop('City',axis=0) # Index drop error
df.drop('City',axis=1) # column drop

df.drop(columns=['City'])
df.drop(2) # 2 == column 2 == index
df.drop(2,axis=0) # label 2 it is a index
df.drop('City') # City is a index
df.drop('City',axis=1)

**Step-5 : Rename**

- rename the column
- rename the index

In [37]:
df["Names"]=["Ramesh","suresh","Satish"]
df["Age"]=[20,24,26]
df["City"]=["Hyd","Pune","Delhi"]
df

    Names  Age   City
0  Ramesh   20    Hyd
1  suresh   24   Pune
2  Satish   26  Delhi

In [38]:
# df.rename(mapper)
# mapper means dictionary
c={'City':'Citi'}
df.rename(c, axis=1) # 1 level

df.rename(columns=c) # 2 Level

    Names  Age   Citi
0  Ramesh   20    Hyd
1  suresh   24   Pune
2  Satish   26  Delhi

**Step-7 : Save the dataframe**

- dataframe can be save into : .csv format
- .xlsx format
- where you want to save:directory
- on what name you want save : name of the file
- on what extension you can use : .csv,.xlsx
- different location : "C:\Users\vaish\Documents\NareshIT\GEN_AI\df1.csv"
- same location : no need to provide directory: 'df1.csv'

In [ ]:
df.to_csv
df.to_excel

In [56]:
df.to_csv(r"C:\Users\vaish\Documents\NareshIT\GEN_AI\df1.csv",index=False)
df.to_csv('df1.csv',index=False)

In [53]:
df.to_csv:(r"C:\Users\vaish\Documents\NareshIT\GEN_AI\df2.csv")

**Step-8 : How to read a Dataframe**

In [57]:
pd.read_csv(r"C:\Users\vaish\Documents\NareshIT\GEN_AI\df1.csv")
pd.read_csv('df1.csv')

    Names  Age   City
0  Ramesh   20    Hyd
1  suresh   24   Pune
2  Satish   26  Delhi

In [ ]:
pd.read_excel(<full path>)